modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "vc"
version = "${version}"
displayName = "Valkyrien Computers"
authors = "TechTastic"
description = '''
Computer-based Mod Integration with Valkyrien Skies addons
'''
logoFile = "assets/vc/textures/item/vc_logo.png"

[[dependencies.vc]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vc]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2,)"
ordering = "AFTER"
side = "BOTH"

#[[dependencies.vc]]
#modId = "create"
#mandatory = true
#versionRange = "[0.5.0e,)"
#ordering = "NONE"
#side = "BOTH"
